version: "3.8"

services:

  # ===================== KAFKA (KRaft mode, NO ZOOKEEPER) =====================
  kafka:
    image: apache/kafka:4.1.1
    container_name: kafka
    networks:
      - linkedin-network
    ports:
      - "9092:9092"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

    volumes:
      - kafka_data:/var/lib/kafka/data

  # ===================== KAFKA UI =====================
  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    container_name: kafka-ui
    networks:
      - linkedin-network
    ports:
      - "8090:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  # ===================== DATABASES =====================
  notification-db:
    image: postgres:15
    container_name: notification-db
    networks:
      - linkedin-network
    environment:
      POSTGRES_DB: notificationDB
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - notification-db-data:/var/lib/postgresql/data

  notification-service:
    image: vishalpatidar123/linkedin-app/notification-service:latest
    container_name: notification-service
    networks:
      - linkedin-network
    depends_on:
      - discovery-server
      - notification-db
      - kafka

# ===================== NETWORKS & VOLUMES =====================
networks:
  linkedin-network:

volumes:
  kafka_data:
  notification-db-data:
  posts-db-data:
  user-db-data:
  connections-db-data: